// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPgv4jSgd7Pi-R3gAHiMUIs7-uPRczBs0',
    appId: '1:63380580708:web:889fa1cd3b04683d4e3271',
    messagingSenderId: '63380580708',
    projectId: 'careerwise-17f8d',
    authDomain: 'careerwise-17f8d.firebaseapp.com',
    storageBucket: 'careerwise-17f8d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY3NwvdIo67jdIH4IzqFoVyfW_y3eD1j0',
    appId: '1:63380580708:android:c5ac1d2e3063b7514e3271',
    messagingSenderId: '63380580708',
    projectId: 'careerwise-17f8d',
    storageBucket: 'careerwise-17f8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGTVUww7JNxeaqPf6JhEDXJ10yONXZcns',
    appId: '1:63380580708:ios:2d5f1fd700f61c564e3271',
    messagingSenderId: '63380580708',
    projectId: 'careerwise-17f8d',
    storageBucket: 'careerwise-17f8d.firebasestorage.app',
    iosBundleId: 'com.example.careerGuidance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGTVUww7JNxeaqPf6JhEDXJ10yONXZcns',
    appId: '1:63380580708:ios:2d5f1fd700f61c564e3271',
    messagingSenderId: '63380580708',
    projectId: 'careerwise-17f8d',
    storageBucket: 'careerwise-17f8d.firebasestorage.app',
    iosBundleId: 'com.example.careerGuidance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPgv4jSgd7Pi-R3gAHiMUIs7-uPRczBs0',
    appId: '1:63380580708:web:feb9cc2b7c30408d4e3271',
    messagingSenderId: '63380580708',
    projectId: 'careerwise-17f8d',
    authDomain: 'careerwise-17f8d.firebaseapp.com',
    storageBucket: 'careerwise-17f8d.firebasestorage.app',
  );
}
